version: "3.8"
services:
  postgresql:
    image: postgres:15
    volumes:
      - temp-facul:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5555:5432
volumes:
  temp-facul:
